version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --all-extras
    - uv run --all-extras mkdocs build -d $READTHEDOCS_OUTPUT/html
