# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    # with adaptations to use workspaces+projects instead of `uv pip`
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs
    - uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html

formats:
  - htmlzip

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
