# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

formats:
  # Temporarily disabling PDF downloads due to problem with nbsphinx in LateX builds
  # - pdf
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  fail_on_warning: false
