# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --group docs --link-mode=copy

formats:
  - pdf
  - htmlzip

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
