# generated by datamodel-codegen:
#   filename:  https://stac-extensions.github.io/eo/v1.1.0/schema.json
#   timestamp: 2026-01-06T17:36:21+00:00
#   datamodel-codegen
#     --output-model-type "pydantic_v2.BaseModel" \
#     --input-file-type jsonschema \
#     --url https://stac-extensions.github.io/eo/v1.1.0/schema.json \
#     --output ./eo.py


from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import (
    BaseModel,
    Field,
    RootModel,
    StringConstraints,
    confloat,
)

from .utils import FieldsModel


class CommonName(Enum):
    coastal = "coastal"
    blue = "blue"
    green = "green"
    red = "red"
    rededge = "rededge"
    yellow = "yellow"
    pan = "pan"
    nir = "nir"
    nir08 = "nir08"
    nir09 = "nir09"
    cirrus = "cirrus"
    swir16 = "swir16"
    swir22 = "swir22"
    lwir = "lwir"
    lwir11 = "lwir11"
    lwir12 = "lwir12"


class Band(BaseModel, validate_assignment=True):
    name: str | None = Field(None, title="Name of the band")
    common_name: CommonName | None = Field(None, title="Common Name of the band")
    description: Annotated[str, StringConstraints(min_length=1)] | None = Field(
        None, title="Description of the band"
    )
    center_wavelength: float | None = Field(None, title="Center Wavelength")
    full_width_half_max: float | None = Field(None, title="Full Width Half Max (FWHM)")
    solar_illumination: Annotated[float, confloat(ge=0.0)] | None = Field(
        None, title="Solar Illumination"
    )


class Bands(RootModel[list[Band]]):
    root: list[Band] = Field(..., min_length=1, title="Bands")

    def __getitem__(self, item: str | int) -> Band:
        if isinstance(item, int):
            return self.root[item]
        else:
            return next(filter(lambda b: item in [b.name, b.common_name], self.root))


class Fields(FieldsModel, validate_assignment=True):
    cloud_cover: Annotated[float, confloat(ge=0.0, le=100.0)] | None = Field(
        None, alias="eo:cloud_cover", title="Cloud Cover"
    )
    snow_cover: Annotated[float, confloat(ge=0.0, le=100.0)] | None = Field(
        None, alias="eo:snow_cover", title="Snow and Ice Cover"
    )
    bands: Bands | None = Field(None, alias="eo:bands")
