#!/bin/bash

set -e

if [[ -n "${PYSTAC_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
TRAVIS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
SRC_DIR="$( cd -P "$( dirname "TRAVIS_DIR" )" && pwd )"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Test that code is compliant with yapf (code formatter) and flake8.
"
}


if [ "${1:-}" = "--help" ]; then
    usage
else
    echo $SRC_DIR

    echo "Checking that library code is consistent with flake8..."
    flake8 "$SRC_DIR/pystac"

    echo "Checking that test code is consistent with flake8..."
    flake8 "$SRC_DIR/tests"

    # Exit code of 1 if yapf has a non-empty diff
    # (ie. scripts/format_code needs to be run)
    echo "Checking that code is consistent with yapf..."
    if !(yapf -dpr "$SRC_DIR/pystac" > /dev/null &&
             yapf -dpr "$SRC_DIR/tests" > /dev/null); then
        echo "Code has not been formatted by yapf."
        exit 1
    fi
fi
