#!/bin/bash

set -e

if [[ -z $ASV_FACTOR ]]; then
    ASV_FACTOR=1.25;
fi

asv continuous --split -e --interleave-rounds \
    --factor ${ASV_FACTOR} \
    --config "${ASV_DIR}/asv.conf.json" \
    main HEAD;
