#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites in CI.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Install/upgrade dependencies
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

        ./scripts/test
    fi
fi
