#!/bin/bash

set -e

echo
echo " -- CHECKING TYPES WITH MYPY --"
echo

mypy docs pystac setup.py tests

echo
echo " -- CHECKING WITH BLACK AND FLAKE8 --"
echo

pre-commit run --all-files

echo
echo " -- CHECKING SPELLING WITH CODESPELL --"
echo

echo
echo " -- LINTING RST FILES WITH DOC8 --"
echo

doc8 docs -q


# Code spelling
codespell -I .codespellignore -f \
    pystac/*.py pystac/**/*.py \
    tests/*.py tests/**/*.py \
    docs/*.rst docs/**/*.rst \
    docs/*.ipynb docs/**/*.ipynb \
    scripts/* \
    *.py \
    *.md
