#!/bin/bash

set -e

echo
echo " -- CHECKING WITH BLACK, DOC8, FLAKE8 AND MYPY --"
echo

pre-commit run --all-files

echo
echo " -- CHECKING SPELLING WITH CODESPELL --"
echo

# Code spelling
codespell -I .codespellignore -f \
    pystac/*.py pystac/**/*.py \
    tests/*.py tests/**/*.py \
    docs/*.rst docs/**/*.rst \
    docs/*.ipynb docs/**/*.ipynb \
    scripts/* \
    *.py \
    *.md
