#!/bin/bash

set -e

if [[ -z ${CI} ]]; then
    source ./scripts/lint
fi

echo
echo " -- RUNNING UNIT TESTS --"
echo

# Test suite with coverage enabled
coverage run --source=pystac/ -m unittest discover tests/
coverage xml
