#!/bin/bash

set -e

if [[ -z ${CI} ]]; then
    pre-commit run --all-files
fi
echo

if [[ -z ${CI} || -n ${CHECK_COVERAGE} ]]; then
    echo " -- RUNNING UNIT TESTS (WITH COVERAGE) --"
    # Test suite with coverage enabled
    coverage run -m pytest tests
else
    echo " -- RUNNING UNIT TESTS (WITHOUT COVERAGE) --"
    pytest tests
fi

echo
