name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pystac
    permissions:
      id-token: write
    if: ${{ github.repository }} == 'stac-utils/pystac'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: "3.x"
      - name: Build 
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
